CREATE DATABASE portal_DB;

\c portal_DB;

CREATE TABLE simulado_questoes (
    id_questao SERIAL PRIMARY KEY UNIQUE NOT NULL,
    ano_prova INTEGER NOT NULL,
    titulo_questao VARCHAR(255),
    texto_questao TEXT,
    questao TEXT NOT NULL,
    imagem VARCHAR(255),
    imagem VARCHAR(255),
    referencia TEXT,
    alternativa_a TEXT,
    alternativa_b TEXT,
    alternativa_c TEXT,
    alternativa_d TEXT,
    alternativa_e TEXT,
    resposta_correta TEXT
);

INSERT INTO simulado_questoes (ano_prova, titulo_questao, texto_questao, imagem, referencia, questao, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, resposta_correta) VALUES
(2014, 'Censura moralista', 
'Ha tempos que a leitura esta em pauta. E, diz-se, em crise. Comenta-se esta crise, por exemplo, apontando a precariedade das praticas de leitura, lamentando a falta de familiaridade dos jovens com livros, reclamando da falta de bibliotecas em tantos municipios, do preco dos livros em livrarias, num nunca acabar de problemas e de carencias. Mas, de um tempo para ca, pesquisas academicas vem dizendo que talvez nao seja exatamente assim, que brasileiros leem, sim, so que leem livros que as pesquisas tradicionais nao levam em conta. E, tambem de um tempo para ca, politicas educacionais tem tomado a peito investir em livros e em leitura.', 
NULL, 'LAJOLO, M. Disponivel em: www.estadao.com.br. Acesso em: 2 dez. 2013.', 'Os falantes, nos textos que produzem, sejam orais ou escritos, posicionam-se frente a assuntos que geram consenso ou despertam polemica. No texto, a autora', 'ressalta a importancia de os professores incentivarem os jovens as praticas de leitura.', 
'critica pesquisas tradicionais que atribuem a falta de leitura a precariedade de bibliotecas.', 'rebate a ideia de que as politicas educacionais sao eficazes no combate a crise de leitura.', 'questiona a existencia de uma crise de leitura com base nos dados de pesquisas academicas.', NULL, 'Gabarito explicado: d) CORRETA. A autora comeca por falar da suposta crise nas praticas de leitura e, num segundo momento, informa que as pesquisas academicas levam a crer que tal crise nao existe.'
),
(2017, NULL, 'Essas mocas tinham o vezo de afirmar o contrario do que desejavam. Notei a singularidade quando principiaram a elogiar o meu paleto cor de macaco. Examinavam-no serias, achavam o pano e os aviamentos de qualidade superior, o feitio admiravel. Envaideci-me: nunca havia reparado em tais vantagens. Mas os gabos se prolongaram, trouxeram-me desconfianca. Percebi afinal que elas zombavam e nao me susceptibilizei. Longe disso: achei curiosa aquela maneira de falar pelo avesso, diferente das grosserias a que me habituara. Em geral me diziam com franqueza que a roupa nao me assentava no corpo, sobrava nos sovacos.', 
NULL, 'RAMOS, G. Infancia. Rio de Janeiro: Record, 1994.', 'Por meio de recursos linguisticos, os textos mobilizam estrategias para introduzir e retomar ideias, promovendo a progressao do tema. No fragmento transcrito, um novo aspecto do tema e introduzido pela expressao', 'a singularidade.', 'tais vantagens.', 'os gabos.', 'Longe disso.', 'Em geral.', 'Gabarito explicado: d) CERTA. Os elogios que as mulheres faziam ao paleto do homem eram, na verdade, ironicos. Quando ele percebeu isso, em vez de ficar ressentido, achou curiosa a ironia das mocas: Longe disso: achei curiosa aquela maneira de falar pelo avesso.'),
(2020, 'Obra Sao Bernardo', 'Leia atentamente e assinale a alternativa correta. Escola! Que me importava que os outros soubessem ler ou fossem analfabetos? Esses homens de governo tem um parafuso frouxo. Metam o pessoal letrado na apanha da mamona. Hao de ver a colheita.', NULL, '[Sao Bernardo, p. 50].', 'Conforme ficamos sabendo logo adiante no enredo, Paulo Honorio decide, apesar do que afirma no trecho destacado, construir uma escola em S. Bernardo porque', 'qualquer fim justifica qualquer meio e nao ha nem bem em si nem mal em si.', 'ha bem e mal, mas qualquer meio para possuir as terras de S. Bernardo e legitimo.', 'todos os meios sao bons em si, mas nao todos os fins.', 'nenhum meio e ruim tendo em vista um fim legitimo.', 'nenhuma finalidade e legitima, mas ha meios bons e meios ruins.', 'Gabarito explicado: d) CORRETA. A autora comeca por falar da suposta crise nas praticas de leitura e, num segundo momento, informa que as pesquisas academicas levam a crer que tal crise nao existe.'
),
(2017, 'A causa secreta', 
'Garcia tinha-se chegado ao cadaver, levantara o lenco e contemplara por alguns instantes as feicoes defuntas. Depois, como se a morte espiritualizasse tudo, inclinou-se e beijou-a na testa. Foi nesse momento que Fortunato chegou a porta. Estacou assombrado; nao podia ser o beijo da amizade, podia ser o epilogo de um livro adultero [...]. Entretanto, Garcia inclinou-se ainda para beijar outra vez o cadaver, mas entao nao pode mais. O beijo rebentou em solucoes, e os olhos nao puderam conter as lagrimas, que vieram em borbotoes, lagrimas de amor calado, e irremediavel desespero. Fortunato, a porta, onde ficara, saboreou tranquilo essa explosao de dor moral que foi longa, muito longa, deliciosamente longa.', 
NULL, 'ASSIS, M. A causa secreta. Disponivel em: www.dominiopublico.gov.br. Acesso em: 9 out. 2015.', 
'No fragmento, o narrador adota um ponto de vista que acompanha a perspectiva de Fortunato. O que singulariza esse procedimento narrativo e o registro do(a)', 'indignacao face a suspeita do adulterio da esposa.', 'tristeza compartilhada pela perda da mulher amada.', 'espanto diante da demonstracao de afeto de Garcia.', 'prazer da personagem em relacao ao sofrimento alheio.', 'superacao do ciume pela comocao decorrente da morte.', 'Gabarito explicado: D) CORRETA. A primeira vez que Fortunato e mencionado no texto e o momento em que ele, chegando a porta, fica surpreso ao ver como Garcia beija a defunta.'
);


INSERT INTO simulado_questoes (ano_prova, titulo_questao, texto_questao, imagem, referencia, questao, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, resposta_correta) VALUES
(2017, NULL, 'Joao/Zero (Wagner Moura) é um cientista genial, mas infeliz porque ha 20 anos atras foi humilhado publicamente durante uma festa e perdeu Helena (Alinne Moraes), uma antiga e eterna paixao. Certo dia, uma experiencia com um de seus inventos permite que ele faca uma viagem no tempo, retornando para aquela época e podendo interferir no seu destino. Mas quando ele retorna, descobre que sua vida mudou totalmente e agora precisa encontrar um jeito de mudar essa historia, nem que para isso tenha que voltar novamente ao passado. Sera que ele conseguira acertar as coisas?', NULL, 'Disponível em: http://adorocinema.com. Acesso em: 4 out. 2011.', 'Qual aspecto da organizacao gramatical atualiza os eventos apresentados na resenha, contribuindo para despertar o interesse do leitor pelo filme?', 'O emprego do verbo haver, em vez de ter, em ha 20 anos atrás foi humilhado.', 'A descricao dos fatos com verbos no presente do indicativo, como retorna e descobre.', 'A repeticao do emprego da conjunçao mas para contrapor ideias.', 'A finalizaçao do texto com a frase de efeito Será que ele conseguirá acertar as coisas?.', 'b) A descriçao dos fatos com verbos no presente do indicativo, como retorna e descobre.'
),
(2014, NULL, 'Os diagramas abaixo ilustram a frequencia percentual de indivíduos com diferentes tamanhos de bico, para duas espécies de tentilhões (genero Geospiza) encontradas em tres ilhas do arquipélago de Galápagos, no oceano Pacífico. As frequencias de indivíduos com bicos de diferentes profundidades (indicadas pelas setas) sao mostradas para cada espécie, em cada ilha. Sabendo-se que ambas as espécies se alimentam de sementes, indique a interpretaçao correta para os resultados apresentados.', 'https://luschettini.github.io/site-portaleducacional/media/img/img-simulado/questao06.png', 'Adaptado de Pianka, E.R. Evolutionary Ecology. Harper & Row, Publishers, New York, 397 pp. 1978. Em: http://goose.ycp.edu/~kkleiner/ecology/lectureimages/15finches.jpg', NULL, 
'Trata-se de um exemplo de cooperaçao entre as duas espécies, que procuram por alimento juntas, quando estao em simpatria.', 'Trata-se de um exemplo de deslocamento de caracteres resultante de competiçao entre as duas espécies na situaçao de simpatria', 'Trata-se de um exemplo de predaçao mútua entre as espécies, levando à exclusao de G. fuliginosa na ilha Daphne, e de G. fortis na ilha Los Hermanos.', 'Trata-se de um caso de repulsa mútua entre as duas espécies, sendo mais perceptível nas ilhas Daphne e Los Hermanos.', 'B) Trata-se de um exemplo de deslocamento de caracteres resultante de competiçao entre as duas espécies na situaçao de simpatria.'),
(2013, NULL, NULL, NULL, 'Unicamp', 'Considerando os respectivos ciclos de vida e de reproduçao, um pinheiro do Paraná pode ser diferenciado de um jequitibá pela', 'ausencia de sementes e presença de flores.', 'ausencia de sementes e de frutos.', 'presenca de sementes e ausencia de frutos.', 'presenca de frutos e ausencia de sementes.', 
'c) Presenca de sementes e ausencia de frutos. O pinheiro-do-paraná (Araucaria angustifolia) é uma gimnosperma, o que significa que ele produz sementes, mas nao frutos. Já o jequitibá é uma angiosperma, que produz tanto sementes quanto frutos.'),
(2013, NULL, NULL, NULL, 'Unicamp', 'Considere um indivíduo heterozigoto para dois locos genicos que estao em linkage, ou seja, nao apresentam segregacao independente. A representacao esquemática dos cromossomos presentes em uma de suas células somáticas em divisao mitotica é:', 'https://luschettini.github.io/site-portaleducacional/media/img/img-simulado/9a.png', 'https://luschettini.github.io/site-portaleducacional/media/img/img-simulado/9b.png', 
'https://luschettini.github.io/site-portaleducacional/media/img/img-simulado/9c.png', 'https://luschettini.github.io/site-portaleducacional/media/img/img-simulado/9d.png', 
'D) Se os genes estao ligados (em linkage) entao eles estao presentes em dois locos genicos distintos do mesmo cromossomo. Assim, as alternativas C e D estao incorretas. Outra informacao que enunciado nos dá é que a célula é somática e está em divisao mitotica. Dessa forma, seus cromossomos estao duplicados, compostos por duas cromátides-irmas. Como as cromátides-irmas sao iguais, entao ambas devem apresentar o mesmo alelo.'
),
(2018, NULL, 'A utilizacao de extratos de origem natural tem recebido a atencao de pesquisadores em todo o mundo, principalmente nos países em desenvolvimento que sao altamente acometidos por doencas infecciosas e parasitárias. Um bom exemplo dessa utilizacao sao os produtos de origem botanica que combatem insetos.', NULL, 'ENEM', 'O uso desses produtos pode auxiliar no controle da:', 'esquistossomose.', 'leptospirose.', 'leishmaniose.', 'hanseníase.', 'c) leishmaniose. A leishmaniose é uma doenca causada por protozoário, sendo transmitida através da picada de um inseto vetor. Existe medicacao para prevenir a doenca somente em seres humanos.');


INSERT INTO simuladoQuestões (ano_prova, titulo_questao, texto_questao, imagem, referencia, questao, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, resposta_correta) VALUES
(2017, 'Projecao Gall-Peters', 
'Esse mapa mostra o tamanho e a proporcao de paises, continentes e oceanos com mais precisao. Uma das principais mudancas e que a Europa aparece muito menor do que se via antes em comparacao com a Africa, que e muito maior.', 
NULL, 'Disponivel em: www.bbc.com/portuguese/internacional-39349115> Acesso em: 10 jan. 2023', 'Os sistemas de projecoes cartograficas constituem-se de formulas matematicas que transformam as coordenadas geograficas, a partir de uma superficie esferica (elipsoidal), em coordenadas planas, mantendo correspondencia entre elas. O uso deste artificio geometrico das projecoes consegue reduzir as deformacoes, mas nunca elimina-las. A projecao de Gall-Peters corresponde a uma projecao', 'afilatica.', 'apolitica', 'azimutal equidistante.', 'conforme.', 
'equivalente.', 'Gabarito explicado: E) CORRETA. A projecao Gall-Peters mantem as proporcoes relativas de areas, sendo classificada como equivalente.'),
(2019, NULL, 'Leia a definicao de tsunami, extraida do site da Comissao Brasileira de Sitios Geologicos (SIGEP). Grande onda ou sucessao de ondas marinhas que se deslocam atraves do oceano por milhares de quilometros em alta velocidade (podem viajar a mais de 700 km/h). Caracteriza-se por ter grande extensao, chegando a ter mais de 100 km de comprimento, nas linhas da costa pode elevar-se a grande altura, (de 30 metros a 40 metros), e invadir violentamente as praias. Tsunami e um dos desastres naturais que podem, com frequencia, atingir dimensoes catastroficas ao provocar a morte de milhares de pessoas. Um tsunami pode ter varias origens.', NULL, 'Disponivel em:sigep.cprm.gov.br/glossario/verbete/tsunami.htm Acesso em: 10 set. 2022', 'Dentre as origens desse fenomeno, e correto citar', 'o aquecimento anormal das aguas do oceano Atlantico.', 'os movimentos de rotacao e de translacao do planeta Terra.', 'as acoes de correntes maritimas frias de origem equatorial.', 'os deslocamentos dos oceanos existentes no nucleo interno do nosso planeta.', 'os tremores sismicos no assoalho oceanico e/ou vulcanismo.', 
'Gabarito explicado: E) CORRETA. Tsunamis sao frequentemente causados por tremores sismicos ou vulcanismo no assoalho oceanico.'),
(2019, NULL, 'Tratava-se agora de construir um ritmo novo. Para tanto, era necessario convocar todas as forcas vivas da Nacao, todos os homens que, com vontade de trabalhar e confianca no futuro, pudessem erguer, num tempo novo, um novo Tempo. E, a grande convocacao que conclamava o povo para a gigantesca tarefa, comecaram a chegar de todos os cantos da imensa patria os trabalhadores: os homens simples e quietos, com pes de raiz, rostos de couro e maos de pedra, e no calcano, em carro de boi, em lombo de burro, em paus-de-arara, por todas as formas possiveis e imaginaveis, em sua mudez cheia de esperanca, muitas vezes deixando para tras mulheres e filhos a aguardar suas promessas de melhores dias; foram chegando de tantos povoados, tantas cidades cujos nomes pareciam cantar saudades aos seus ouvidos, dentro dos antigos ritmos da imensa patria... Terra de sol, Terra de luz… Brasil! Brasil! Brasilia!', NULL, 'MORAES, V.; JOBIM, A. C. Brasilia, sinfonia da alvorada. III – A chegada dos candangos. Disponivel em: www.viniciusdemoraes.com.br. Acesso em: 14 ago. 2012 (adaptado)', 'No texto, a narrativa produzida sobre a construcao de Brasilia articula os elementos politicos e socioeconomicos indicados, respectivamente, em:', 'Apelo simbolico e migracao inter-regional.', 'Organizacao sindical e expansao do capital.', 'Seguranca territorial e estabilidade financeira.', 'Consenso partidario e modernizacao rodoviaria.', 'Perspectiva democratica e eficacia dos transportes.', 'A alternativa correta e a) Apelo simbolico e migracao inter-regional. O texto evoca um forte apelo simbolico ao descrever a construcao de Brasilia como um novo tempo e a chegada de trabalhadores de todas as partes do pais, ilustrando um processo de migracao inter-regional. Isso reforca o simbolismo de Brasilia como um projeto de uniao nacional e desenvolvimento.'),
(2019, NULL, '-O fenomeno da mobilidade populacional vem, desde as ultimas decadas do seculo XX, apresentando transformacoes significativas no seu comportamento, nao so no Brasil como tambem em outras partes do mundo. Esses novos processos se materializam, entre outros aspectos, na dimensao interna, pelo redirecionamento dos fluxos migratorios para as cidades medias, em detrimento dos grandes centros urbanos; pelos deslocamentos de curta duracao e a distancias menores; pelos movimentos pendulares, que passam a assumir maior relevancia nas estrategias de sobrevivencia, nao mais restritos aos grandes aglomerados urbanos.', NULL, 'OLIVEIRA, L. A. P.; OLIVEIRA, A. T. R. Reflexoes sobre os deslocamentos populacionais no Brasil. Rio de Janeiro: IBGE, 2011 (adaptada).', ',A redefinicao dos fluxos migratorios internos no Brasil, no periodo apontado no texto, tem como causa a intensificacao do processo de', 'descapitalizacao do setor primário.', 'ampliacao da economia informal.', 'tributacao da área residencial citadina.', 'desconcentracao da atividade industrial.
', 'saturacao da empregabilidade no setor terciário.', 'Gabarito explicado: D) CORRETA. O fato de descrever algo que aconteceu, mas utilizar verbos no presente, desperta interesse nas pessoas (Mas quando ele retorna, descobre que sua vida mudou totalmente).'),
(2019, NULL, 'Leia a definicao de tsunami, extraida do site da Comissao Brasileira de Sitios Geologicos (SIGEP). Adam Smith (1723 - 1790) escreveu A Riqueza das Nacoes, obra que se constitui como um grande baluarte do capitalismo liberal', NULL, 'ENEM', 'Acerca do pensamento desse autor, assinale a alternativa CORRETA.', 'Criticava o mercantilismo e considerava que a terra era a fonte de toda a riqueza das nacoes, fosse em sua condicao de propriedade comerciavel ou em sua condicao de espaco de producao.', 'Defendia a intervencao do Estado na economia de todas as nacoes como forma de se garantir a igualdade e a justica social.', 'Criticava o mercantilismo e alegava que, com a concorrencia, a divisao do trabalho e o livre comercio, a sociedade como um todo se desenvolveria. Defendia ainda que o trabalho era a principal riqueza de uma nacao.', 'Preconizava a privatizacao de empresas publicas como forma de se garantir o Laissez-faire, ou seja, a produtividade, uma vez que as estatais sempre foram consideradas mal dirigidas e ineficientes.', 'Influenciado por Saint-Simon defendia uma melhor distribuicao da renda nacional.', 'A alternativa correta e c) Criticava o mercantilismo e alegava que, com a concorrencia, a divisao do trabalho e o livre comercio, a sociedade como um todo se desenvolveria. Defendia ainda que o trabalho era a principal riqueza de uma nacao.'),
(2018, 'Lava Mae', 'Creating Showers on Wheels for the Homeless San Francisco, according to recent city numbers, has 4,300 people living on the streets. Among the many problems the homeless face is little or no access to showers. San Francisco only has about 16 to 20 shower stalls to accommodate them. But Doniece Sandoval has made it her mission to change that. The 51-year-old former marketing executive started Lava Mae, a sort of showers on wheels, a new project that aims to turn decommissioned city buses into shower stations for the homeless. Each bus will have two shower stations and Sandoval expects that they ll be able to provide 2,000 showers a week.', NULL, 'ANDREANO, C. Disponivel em: abcnews.go.com. Acesso: 26 jun. 2015 (adaptado).', 'A relacao dos vocabulos shower, bus e homeless, no texto, refere-se a:', 'empregar moradores de rua em lava a jatos para onibus.', 'criar acesso a banhos gratuitos para moradores de rua.', 'comissionar sem-teto para dirigir os onibus da cidade.', 'exigir das autoridades que os onibus municipais tenham banheiros.', 'abrigar dois mil moradores de rua em onibus que foram adaptados.', 'Gabarito explicado: A resposta correta e a opcao b) criar acesso a banhos gratuitos para moradores de rua. O texto fala de um projeto chamado Lava Mae, que consiste em transformar onibus em estacoes de banho para moradores de rua. Shower significa banho de chuveiro, bus significa onibus e homeless significa morador de rua.'),
(2017, 'Israel Travel Guide', 'Israel has always been a standout destination. From the days of prophets to the modern day nomad this tiny slice of land on the eastern Mediteranean has long attracted visitors. While some arrive in the Holy Land on a spiritual quest, many others are on cultural tours, beach holidays and eco-tourism trips. Weeding through Israels convoluted history is both exhilarating and exhausting. There are crumbling temples, ruined cities, abandoned forts and hundreds of places associated with the Bible. And while a sense of adventure is required, most sites are safe and easily accessible. Most of all, Israel is about its incredibly diverse population. Jews come from all over the world to live here, while about 20% of the population is Muslim. Politics are hard to get away from in Israel as everyone has an opinion on how to move the country forward - with a ready ear youre sure to hear opinions from every side of the political spectrum.', NULL, 'Disponivel em: www.worldtravelguide.net. Acesso em: 15 jun. 2012.', 'Antes de viajar, turistas geralmente buscam informaçoes sobre o local para onde pretendem ir. O trecho do guia de viagens de Israel:', 'descreve a historia desse local para que turistas valorizem seus costumes milenares.', 'informa habitos religiosos para auxiliar turistas a entenderem as diferenças culturais.', 'divulga os principais pontos turisticos para ajudar turistas a planejarem sua viagem.', 'recomenda medidas de segurança para alertar turistas sobre possiveis riscos locais.', 'apresenta aspectos gerais da cultura do pais para continuar a atrair turistas estrangeiros.', 'Gabarito explicado: A resposta correta e a opçao e) apresenta aspectos gerais da cultura do pais para continuar a atrair turistas estrangeiros. Ao descrever Israel, o guia de viagens afirma que existem templos desmoronando, cidades em ruinas, fortes abandonados e centenas de locais relacionados com a Biblia. Alem disso, tambem e abordado o fato de o pais ter uma populaçao muito diversificada, composta por judeus do mundo todo e por muçulmanos. O texto tambem afirma que e dificil escapar da politica ja que todas as pessoas tem opinoes sobre como fazer o pais progredir.'),
(2017, NULL, NULL, 'https://luschettini.github.io/site-portaleducacional/media/img/img-simulado/questao18.png', 'KEEFER, M. Disponivel em: www.nj.com. Acesso em: 3 dez. 2018.', 'No cartum, o estudante faz uma pergunta usando turn this thing on por:', 'suspeitar que o colega esta com seu material por engano.', 'duvidar que o colega possa se tornar um bom aluno.', 'desconfiar que o livro levado e de outra materia.', 'entender como desligada a postura do colega.', 'desconhecer como usar um livro impresso.', 'Gabarito explicado: A resposta correta e a opçao e) desconhecer como usar um livro impresso. A expressao "turn this thing on" faz referencia a ligar algo, geralmente relacionado a dispositivos eletronicos. No contexto do cartum, o estudante parece nao saber como manusear um livro impresso, confundindo-o com um aparelho eletronico, o que sugere que ele nao esta familiarizado com o uso de livros fisicos.'),
(NULL, 'Things We Carry on the Sea', NULL, 'https://luschettini.github.io/site-portaleducacional/media/img/img-simulado/questao19.png', 'PING, W. Disponivel em: https://poets.org. Acesso em: 1 jun. 2023.', 'Ao retratar a trajetoria de refugiados, o poema recorre à imagem de viagem maritima para destacar o(a):', 'risco de choques culturais.', 'impacto do ensino de historia.', ' importancia da luta ambiental.', 'existencia de experiencias plurais.', 'necessidade de capacitaçao profissional.', 'Gabarito explicado: A resposta correta e a opçao d) existencia de experiencias plurais. O poema retrata a trajetoria dos refugiados, destacando a diversidade de experiencias que eles carregam consigo, como memorias, diplomas, tradiçoes, e as adversidades enfrentadas. A imagem da viagem maritima simboliza essa pluralidade de vivencias, mostrando tanto as lutas e tragedias, como os sonhos e esperanças. Assim, a opçao que melhor reflete o conteudo do poema e a "d", que aborda a pluralidade de experiencias dos refugiados.'),
(2017, NULL, 'Dont write in English, they said, English is not your mother tongue… ...The language I speak Becomes mine, its distortions, its queerness All mine, mine alone, it is half English, half Indian, funny perhaps, but it is honest, It is as human as I am human… ...It voices my joys, my longings my Hopes... (Kamala Das, 1965:10)', NULL, 'GARGESH, R. South Asian Englishes. In: KACHRU, B.B.; KACHRU, Y.; NELSON, C.L. (Eds.). The Handbook of World English. Singapore: Blackwell, 2006', 'A poetisa Kamala Das, como muitos escritores indianos, escreve suas obras em ingles, apesar de essa nao ser sua primeira lingua. Nesses versos, e:', 'usa a lingua inglesa como efeito humoristico.', 'recorre a vozes de varios escritores ingleses.', 'adverte sobre o uso distorcido da lingua inglesa.', 'demonstra consciencia de sua identidade linguistica.', 'reconhece a incompreensao na sua maneira de falar ingles.', 'Gabarito explicado: A resposta correta e a opçao d) demonstra consciencia de sua identidade linguistica. Apesar das opinioes que consideram que Kamala Das nao deveria escrever em ingles por essa nao ser sua lingua materna, a poetisa afirma o idioma que ela fala se torna seu. Kamala diz que seu idioma e uma mistura de ingles com indiano, que talvez seja engraçada, mas que e honesta e que da voz às suas alegrias, aos seus desejos e às suas esperanças.'),
(NULL, NULL, 'Texto II: O conceito de ready-made, criado por Marcel Duchamp, desafia as convençoes tradicionais de arte ao selecionar objetos comuns e eleva-los ao status de obra de arte, sem qualquer manipulaçao estetica. Sua peça mais iconica, Fonte (um urinol assinado "R. Mutt"), introduziu um novo entendimento sobre o que pode ser considerado arte. Ao expor um objeto de uso cotidiano em galerias, Duchamp questionou o papel do artista e da propria arte.', 'https://luschettini.github.io/site-portaleducacional/media/img/img-simulado/questao21.jpg', 'A fonte, atribuida a Marcel Duchamp. Foto: shutterstock.', 'A obra Fonte de Duchamp e seu conceito de ready-made propoem:', 'A valorizaçao do processo de manufatura de objetos artisticos.', 'A desvalorizaçao total da estetica como criterio artistico.', 'A celebraçao dos objetos produzidos em massa pela sociedade industrial.', 'Uma reflexao critica sobre a definiçao e os limites da arte.', ' A tentativa de imitar tecnicas artisticas classicas por meio de objetos cotidianos.', 'Gabarito explicado: A resposta correta e a opçao d) Uma reflexao critica sobre a definiçao e os limites da arte. Marcel Duchamp, com sua obra Fonte e o conceito de ready-made, questionou os criterios tradicionais da arte ao elevar objetos comuns a status de obra de arte, sem manipulaçao estetica, propondo uma reflexao sobre o que define a arte.'),
(NULL, NULL, 'Texto II: Stephen Lund, artista canadense, morador em Victoria, capital da Columbia Britanica (Canada), transformou-se em fenomeno mundial produzindo obras de arte virtuais pedalando sua bike. Seguindo rotas traçadas com o auxilio de um dispositivo de GPS, ele calcula ter percorrido mais de 10 mil quilometros.', 'https://luschettini.github.io/site-portaleducacional/media/img/img-simulado/questao22.jpg', 'Disponivel em: www.booooooom.com. Acesso em: 9 dez. 2017 (adaptado)./BRACCO, A; LOSCHI, M. Quando rotas se tornam arte. Retratos: a revista do IBGE. Rio de Janeiro, n. 3, set. 2017 (adaptado).', 'Os textos destacam a inovaçao artistica proposta por Stephen Lund a partir do(a):', 'deslocamento das tecnologias de suas funçoes habituais.', 'perspectiva de funcionamento do dispositivo de GPS.', 'ato de guiar sua bicicleta pelas ruas da cidade.', 'analise dos problemas de mobilidade urbana.', ' foco na promoçao cultural da sua cidade.', 'Gabarito explicado: A resposta correta e a opçao a) descolamento das tecnologias de suas funçoes habituais. O GPS e um equipamento eletronico com funçao de apontar direcionamentos aos usuarios de acordo com uma logica pratica e objetiva no que diz respeito à mobilidade. Entretanto, o artista utiliza o GPS como ferramenta de criacao artistica, transformando rotas urbanas em desenhos elaborados e transferidos para os mapas da cidades. Portanto, ele desloca as funcoes originais dessa tecnologia criando uma nova funcao, no caso, o desenho.'),
(2018, NULL, NULL, 'https://luschettini.github.io/site-portaleducacional/media/img/img-simulado/questao23.jpeg', NULL, 'As duas imagens sao producoes que tem a ceramica como materia-prima. A obra Estrutura vertical dupla se distingue da urna funeraria marajoara ao:', 'evidenciar a simetria na disposicao das pecas.', 'materializar a tecnica sem funcao utilitaria.', 'abandonar a regularidade na composicao.', 'anular possibilidades de leituras afetivas.', ' integrar o suporte em sua constituicao.', 'Gabarito explicado: A resposta correta e a opcao b) materializar a tecnica sem funcao utilitaria. Na obra escultorica apresentada no TEXTO I, a ceramica e apresentada como suporte para a arte com caracteristica estetica e conceitual, sem funcao utilitaria. Ja no TEXTO II, a urna funeraria marajoara possui a funcao de conter os restos mortais de um ser humano, tendo portanto um objetivo pratico na sociedade em que foi produzida.'),
(2018, NULL, 'Texto II: Ao ser questionado sobre seu processo de criacao de ready-mades, Marcel Duchamp afirmou: - Isto dependia do objeto; em geral, era preciso tomar cuidado com o seu look . e muito dificil escolher um objeto porque depois de quinze dias voce comeca a gostar dele ou a detesta-lo. e preciso chegar a qualquer coisa com uma indiferenca tal que voce nao tenha nenhuma emocao estetica. A escolha do ready-made e sempre baseada na indiferenca visual e, ao mesmo tempo, numa ausencia total de bom ou mau gosto.', 'https://luschettini.github.io/site-portaleducacional/media/img/img-simulado/questao24.jpg', 'CABANNE, P.Marcel Duchamp: engenheiro do tempo perdido. Sao Paulo: Perspectiva, 1987 (adaptado).', 'Relacionando o texto e a imagem da obra, entende-se que o artista Marcel Duchamp, ao criar os ready-mades, inaugurou um modo de fazer arte que consiste em:', 'designar ao artista de vanguarda a tarefa de ser o artificie do seculo XX.', 'considerar a forma dos objetos como elemento essencial da obra de arte.', 'revitalizar de maneira radical o conceito classico do belo na arte.', 'criticar os principios que determinam o que e uma obra de arte.', ' atribuir aos objetos industriais o status de obra de arte.', 'Gabarito explicado: A resposta correta e a opcao d) criticar os principios que determinam o que e uma obra de arte. Duchamp integrou o movimento de vanguarda dadaista, que tinha como um dos principios questionar a obra de arte como uma atitude "antiarte". Portanto, ao colocar em um salao de exposicoes um objeto ja produzido anteriormente, o artista questiona os motivos que apontam e definem o que e ou nao uma obra de arte.'),
(2016, NULL, NULL, 'https://luschettini.github.io/site-portaleducacional/media/img/img-simulado/questao25.jpeg', 'ROTELLA, M. Marilyn, 1962. Disponivel em: www.nyu.edu. Acesso em: 30 maio 2016.', 'A tecnica da decollage, utilizada pelo artista Mimmo Rotella em sua obra Marilyn, e um procedimento artistico representativo da decada de 1960 por:', 'visar a conservacao das representacoes e dos registros visuais.', 'basear-se na reciclagem de material grafico, contribuindo para a sustentabilidade.', 'aencobrir o passado, abrindo caminho para novas formas plasticas, pela releitura.',  'fazer conviver campos de expressao diferentes e integrar novos significados.', 'abolir o trabalho manual do artista na confeccao das imagens recontextualizadas.', 'Gabarito explicado: A resposta correta e a opcao d) fazer conviver campos de expressao diferentes e integrar novos significados. A decollage e uma tecnica que consiste em aplicar superficies umas sobre as outras e depois descolar camadas de papel a fim de revelar as superficies que estao ocultas. Assim, e um procedimento diferente da colagem, mas que se relaciona com ela e tem tambem a intencao de aliar diversos tipos de comunicacao e expressao, trazendo novas interpretacoes.');

