CREATE DATABASE portal_DB;

\c portal_DB;

CREATE TABLE simuladoQuestões (
    id_questao SERIAL PRIMARY KEY UNIQUE NOT NULL,
    ano_prova INTEGER NOT NULL,
    titulo_questao TEXT,
    texto_questao TEXT,
    questao TEXT NOT NULL,
    imagem NVARCHAR(255),
    referencia TEXT,
    alternativa_a TEXT,
    alternativa_b TEXT,
    alternativa_c TEXT,
    alternativa_d TEXT,
    alternativa_e TEXT,
    resposta_correta TEXT
);

INSERT INTO simuladoQuestões (ano_prova, titulo_questao, texto_questao, imagem, referencia, questao, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, resposta_correta) VALUES
(2014, 'Censura moralista', 'Há tempos que a leitura está em pauta. E, diz-se, em crise. Comenta-se esta crise, por exemplo, apontando a precariedade das práticas de leitura, lamentando a falta de familiaridade dos jovens com livros, reclamando da falta de bibliotecas em tantos municípios, do preço dos livros em livrarias, num nunca acabar de problemas e de carências. Mas, de um tempo para cá, pesquisas acadêmicas vêm dizendo que talvez não seja exatamente assim, que brasileiros leem, sim, só que leem livros que as pesquisas tradicionais não levam em conta. E, também de um tempo para cá, políticas educacionais têm tomado a peito investir em livros e em leitura.', null, 'LAJOLO, M. Disponível em: www.estadao.com.br. Acesso em: 2 dez. 2013.', 'Os falantes, nos textos que produzem, sejam orais ou escritos, posicionam-se frente a assuntos que geram consenso ou despertam polêmica. No texto, a autora', 'ressalta a importância de os professores incentivarem os jovens às práticas de leitura.', 'critica pesquisas tradicionais que atribuem a falta de leitura à precariedade de bibliotecas.', 'rebate a ideia de que as políticas educacionais são eficazes no combate à crise de leitura.', 'questiona a existência de uma crise de leitura com base nos dados de pesquisas acadêmicas.', null, 'Gabarito explicado: d) CORRETA. A autora começa por falar da suposta crise nas práticas de leitura e, num segundo momento, informa que as pesquisas acadêmicas levam a crer que tal crise não existe.'),
(2017, null, 'Essas moças tinham o vezo de afirmar o contrário do que desejavam. Notei a singularidade quando principiaram a elogiar o meu paletó cor de macaco. Examinavam-no sérias, achavam o pano e os aviamentos de qualidade superior, o feitio admirável. Envaideci-me: nunca havia reparado em tais vantagens. Mas os gabos se prolongaram, trouxeram-me desconfiança. Percebi afinal que elas zombavam e não me susceptibilizei. Longe disso: achei curiosa aquela maneira de falar pelo avesso, diferente das grosserias a que me habituara. Em geral me diziam com franqueza que a roupa não me assentava no corpo, sobrava nos sovacos.', null, 'RAMOS, G. Infância. Rio de Janeiro: Record, 1994.', 'Por meio de recursos linguísticos, os textos mobilizam estratégias para introduzir e retomar ideias, promovendo a progressão do tema. No fragmento transcrito, um novo aspecto do tema é introduzido pela expressão', '"a singularidade".', '"tais vantagens".', '"os gabos".', '"Longe disso".', '"Em geral".', 'Gabarito explicado: d) CERTA. Os elogios que as mulheres faziam ao paletó do homem eram, na verdade, irônicos. Quando ele percebeu isso, em vez de ficar ressentido, achou curiosa a ironia das moças: “Longe disso: achei curiosa aquela maneira de falar pelo avesso”.'),
(2020, 'Obra São Bernardo', 'Leia atentamente e assinale a alternativa correta. – Escola! Que me importava que os outros soubessem ler ou fossem analfabetos? Esses homens de governo tem um parafuso frouxo. Metam o pessoal letrado na apanha da mamona. Hão de ver a colheita.', null, '[São Bernardo, p. 50].', 'Conforme ficamos sabendo logo adiante no enredo, Paulo Honório decide, apesar do que afirma no trecho destacado, construir uma escola em S. Bernardo porque', 'qualquer fim justifica qualquer meio e não há nem bem em si nem mal em si.', ' há bem e mal, mas qualquer meio para possuir as terras de S. Bernardo é legítimo.', 'todos os meios são bons em si, mas não todos os fins.', 'nenhum meio é ruim tendo em vista um fim legítimo.', 'nenhuma finalidade é legítima, mas há meios bons e meios ruins', 'Gabarito explicado: d) CORRETA. A autora começa por falar da suposta crise nas práticas de leitura e, num segundo momento, informa que as pesquisas acadêmicas levam a crer que tal crise não existe.'),
(null, 'O Ateneu', 'Leia as duas citações a seguir, extraídas do início e do final de O Ateneu:

“Lembramo-nos, entretanto, com saudade hipócrita, dos felizes tempos; como se a mesma incerteza de hoje, sob outro aspecto, não nos houvesse perseguido outrora e não viesse de longe a enfiada das decepções que nos ultrajam. Eufemismo, os felizes tempos, eufemismo apenas, igual aos outros que nos alimentam, a saudade dos dias que correram como melhores. Bem considerando, a atualidade é a mesma em todas as datas. Feita a compensação dos desejos que variam, das aspirações que se transformam, alentadas perpetuamente do mesmo ardor, sobre a mesma base fantástica de esperanças, a atualidade é uma (...)”. “Aqui suspendo a crônica das saudades. Saudades verdadeiramente? Puras recordações, saudades talvez, se ponderarmos que o tempo é a ocasião passageira dos fatos, mas sobretudo — o funeral para sempre das horas.”', null, '(POMPEIA, Raul. O Atheneu (Chronica de saudades). Rio de Janeiro: Tipografia de Gazeta de Notícias, p 3-4 e 368, 1888.)', 'Com base nessas duas citações, é possível afirmar que, ao fim da narrativa de Sérgio sobre sua vida no colégio, o narrador', 'idealiza a felicidade experimentada na infância, suas aspirações, seu ardor e suas esperanças.', 'considera que a felicidade passada não era maior que a do presente, pois os tempos são iguais.', 'duvida da própria saudade, separando as lembranças relativas ao passado daquele sentimento associado a elas.', 'denuncia a hipocrisia da saudade que sente, por saber que a passagem do tempo é incerta.', null, 'Alternativa correta: d)'),
(2017, 'A causa secreta', 'Garcia tinha-se chegado ao cadáver, levantara o lenço e contemplara por alguns instantes as feições defuntas. Depois, como se a morte espiritualizasse tudo, inclinou-se e beijou-a na testa. Foi nesse momento que Fortunato chegou à porta. Estacou assombrado; não podia ser o beijo da amizade, podia ser o epílogo de um livro adúltero [...]. Entretanto, Garcia inclinou-se ainda para beijar outra vez o cadáver, mas então não pôde mais. O beijo rebentou em soluços, e os olhos não puderam conter as lágrimas, que vieram em borbotões, lágrimas de amor calado, e irremediável desespero. Fortunato, à porta, onde ficara, saboreou tranquilo essa explosão de dor moral que foi longa, muito longa, deliciosamente longa.', null, 'ASSIS, M. A causa secreta. Disponível em: www.dominiopublico.gov.br. Acesso em: 9 out. 2015.', 'No fragmento, o narrador adota um ponto de vista que acompanha a perspectiva de Fortunato. O que singulariza esse procedimento narrativo é o registro do(a)', 'indignação face à suspeita do adultério da esposa.', 'tristeza compartilhada pela perda da mulher amada.', 'espanto diante da demonstração de afeto de Garcia.', 'prazer da personagem em relação ao sofrimento alheio.', 'superação do ciúme pela comoção decorrente da morte.', 'Gabarito explicado: D) CORRETA. A primeira vez que Fortunato é mencionado no texto é o momento em que ele, chegando à porta, fica surpreso ao ver como Garcia beija a defunta.'),
(2017, null, 'João/Zero (Wagner Moura) é um cientista genial, mas infeliz porque há 20 anos atrás foi humilhado publicamente durante uma festa e perdeu Helena (Alinne Moraes), uma antiga e eterna paixão. Certo dia, uma experiência com um de seus inventos permite que ele faça uma viagem no tempo, retornando para aquela época e podendo interferir no seu destino. Mas quando ele retorna, descobre que sua vida mudou totalmente e agora precisa encontrar um jeito de mudar essa história, nem que para isso tenha que voltar novamente ao passado. Será que ele conseguirá acertar as coisas?', null, 'Disponível em: http://adorocinema.com. Acesso em: 4 out. 2011.', 'Qual aspecto da organização gramatical atualiza os eventos apresentados na resenha, contribuindo para despertar o interesse do leitor pelo filme?', 'O emprego do verbo haver, em vez de ter, em “há 20 anos atrás foi humilhado”.', 'A descrição dos fatos com verbos no presente do indicativo, como “retorna” e “descobre”.', 'A repetição do emprego da conjunção “mas” para contrapor ideias.', 'A finalização do texto com a frase de efeito “Será que ele conseguirá acertar as coisas?”.', 'é a b) A descrição dos fatos com verbos no presente do indicativo, como “retorna” e “descobre”.'),
(2014, null, 'Os diagramas abaixo ilustram a frequência percentual de indivíduos com diferentes tamanhos de bico, para duas espécies de tentilhões (gênero Geospiza) encontradas em três ilhas do arquipélago de Galápagos, no oceano Pacífico. As frequências de indivíduos com bicos de diferentes profundidades (indicadas pelas setas) são mostradas para cada espécie, em cada ilha. Sabendo-se que ambas as espécies se alimentam de sementes, indique a interpretação correta para os resultados apresentados.', 'https://luschettini.github.io/site-portaleducacional/media/img/img-simulado/questao06.png', 'Adaptado de Pianka, E.R. Evolutionary Ecology. Harper & Row, Publishers, New York, 397 pp. 1978. Em: http://goose.ycp.edu/~kkleiner/ecology/lectureimages/15finches.jpg', null, 'Trata-se de um exemplo de cooperação entre as duas espécies, que procuram por alimento juntas, quando estão em simpatria.', 'Trata-se de um exemplo de deslocamento de caracteres resultante de competição entre as duas espécies na situação de simpatria', 'Trata-se de um exemplo de predação mútua entre as espécies, levando à exclusão de G. fuliginosa na ilha Daphne, e de G. fortis na ilha Los Hermanos.', 'Trata-se de um caso de repulsa mútua entre as duas espécies, sendo mais perceptível nas ilhas Daphne e Los Hermanos.', null, 'Gabarito explicado: B) Trata-se de um exemplo de deslocamento de caracteres resultante de competição entre as duas espécies na situação de simpatria.'),
(2013, null, null, null, 'Unicamp', 'Considerando os respectivos ciclos de vida e de reprdução, um pinheiro do Paraná pode ser diferenciado de um jequitibá pela', 'ausência de sementes e presença de flores.', 'ausência de sementes e de frutos.', 'presença de sementes e ausência de frutos.', 'presença de frutos e ausência de sementes.', null, 'A alternativa correta é a c) presença de sementes e ausência de frutos. O pinheiro-do-paraná (Araucaria angustifolia) é uma gimnosperma, o que significa que ele produz sementes, mas não frutos. Já o jequitibá é uma angiosperma, que produz tanto sementes quanto frutos. Portanto, a presença de sementes e a ausência de frutos é uma característica que diferencia o pinheiro-do-paraná do jequitibá.'),
(2013, null, null, null, 'Unicamp', 'Considere um indivíduo heterozigoto para dois locos gênicos que estão em linkage, ou seja, não apresentam segregação independente. A representação esquemática dos cromossomos presentes em uma de suas células somáticas em divisão mitótica é:', 'https://luschettini.github.io/site-portaleducacional/media/img/img-simulado/9a.png', 'https://luschettini.github.io/site-portaleducacional/media/img/img-simulado/9b.png', 'https://luschettini.github.io/site-portaleducacional/media/img/img-simulado/9c.png', 'https://luschettini.github.io/site-portaleducacional/media/img/img-simulado/9d.png', null, 'Se os genes estão ligados (em linkage) então eles estão presentes em dois locos gênicos distintos do mesmo cromossomo. Assim, as alternativas C e D estão incorretas. Outra informação que enunciado nos dá é que a célula é somática e está em divisão mitótica. Dessa forma, seus cromossomos estão duplicados, compostos por duas cromátides-irmãs. Como as cromátides-irmãs são iguais, então ambas devem apresentar o mesmo alelo.'),
(2018, null, 'A utilização de extratos de origem natural tem recebido a atenção de pesquisadores em todo o mundo, principalmente nos países em desenvolvimento que são altamente acometidos por doenças infecciosas e parasitárias. Um bom exemplo dessa utilização são os produtos de origem botânica que combatem insetos.', null, 'ENEM', 'O uso desses produtos pode auxiliar no controle da:', 'esquistossomose.', 'leptospirose.', 'leishmaniose.', 'hanseníase.', null, 'Gabarito explicado: A resposta correta é a opção c) leishmaniose. A leishmaniose é uma doença causada por protozoário, sendo transmitida através da picada de um inseto vetor. Existe medicação para prevenir a doença somente em seres humanos.');


