-- Criação da tabela de Carreiras  
CREATE TABLE carreiras(
    id SERIAL PRIMARY KEY,
    titulo VARCHAR(225) NOT NULL, 
    descricao TEXT NOT NULL,
    mercado TEXT NOT NULL,
    salario VARCHAR(50),
    link_cursoSenai VARCHAR(200),
    link_faculdadeSenai VARCHAR(200)
);

INSERT INTO carreiras (titulo, descricao, mercado, salario, link_cursoSenai, link_faculdadeSenai)
VALUES
('Técnico em Automação Industrial', 'O Técnico em Automação Industrial é responsável por projetar, instalar e manter sistemas automatizados que controlam processos em fábricas e indústrias. Ele programa dispositivos como controladores lógicos programáveis (CLPs) e sensores para coordenar máquinas de produção, garantindo maior eficiência, segurança e redução de custos.', 'Indústrias de alimentos, bebidas, automobilística...', 'R$ 2.500 a R$ 8.000', 'https://www.sp.senai.br/curso/tecnico-em-automacao-industrial/95708', 'https://faculdades.sp.senai.br/curso/77171/automacao-industrial'),
('Técnico de Fabricação Mecânica', 'O Técnico em Fabricação Mecânica é responsável por projetar, fabricar e montar peças e componentes mecânicos, como peças de carros, tratores, eletrodomésticos e ferramentas para a construção civil. Eles trabalham com matérias-primas e utilizam processos de usinagem, soldagem e fundição para criar produtos finais.', 'Indústrias de metalurgia, petróleo e gás, e usinagem.', 'R$5.606,99', 'https://www.sp.senai.br/curso/tecnico-de-fabricacao-mecanica/95709', 'https://faculdades.sp.senai.br/curso/77172/fabricacao-mecanica'),
('Técnico em Eletrotécnica', 'O Técnico em Eletrotécnica projeta, instala e realiza a manutenção de sistemas elétricos industriais e prediais. Ele trabalha com redes de energia, máquinas elétricas, geradores e sistemas de alta tensão, garantindo que as operações sejam seguras e eficientes.', 'Construtoras, concessionárias de energia e empresas de manutenção.', 'R$ 2.500 a R$ 7.000.', 'https://www.sp.senai.br/curso/tecnico-em-eletrica/95710', 'https://faculdades.sp.senai.br/curso/77173/eletrica'),
('Técnico em Logística', 'O Técnico em Logística planeja e gerencia o fluxo de mercadorias em uma empresa, desde o armazenamento até a entrega ao cliente final. Ele organiza rotas, controla estoques e supervisiona operações de transporte para otimizar prazos e reduzir custos.', 'Transportadoras, centros de distribuição e empresas de comércio.', 'R$ 2.000 a R$ 5.000', 'https://www.sp.senai.br/curso/tecnico-em-logistica/95711', 'https://faculdades.sp.senai.br/curso/77174/logistica'),
('Técnico Desenvolvimento de Sistemas', 'O Técnico em Desenvolvimento de Sistemas projeta, desenvolve e mantém software para diferentes aplicações, como sistemas empresariais e aplicativos. Ele escreve códigos, gerencia bancos de dados e implementa soluções tecnológicas para melhorar os processos de empresas.', ' Empresas de tecnologia, startups e indústrias.', 'R$ 3.000 a R$ 8.000', 'https://www.sp.senai.br/curso/tecnico-em-desenvolvimento-de-sistemas/95712', 'https://faculdades.sp.senai.br/curso/77175/desenvolvimento-de-sistemas'),
('Técnico em Edificações', 'O Técnico em Edificações é responsável por elaborar projetos arquitetônicos e acompanhar obras de construção civil. Ele realiza cálculos estruturais, prepara orçamentos e supervisiona etapas de obras, garantindo que sejam executadas dentro dos padrões técnicos e legais.', 'Construtoras, empreiteiras e órgãos públicos.', ' R$ 2.500 a R$ 6.500', 'https://www.sp.senai.br/curso/tecnico-em-edificacao/95713', 'https://faculdades.sp.senai.br/curso/77176/edificacao'),

--
CREATE TABLE simuladoQuestões (
    id_questao SERIAL PRIMARY KEY UNIQUE NOT NULL,
    ano_prova INTEGER NOT NULL,
    titulo_questao TEXT,
    texto_questao TEXT,
    questao TEXT NOT NULL,
    imagem NVARCHAR(255),
    referencia TEXT,
    alternativa_a TEXT,
    alternativa_b TEXT,
    alternativa_c TEXT,
    alternativa_d TEXT,
    alternativa_e TEXT,
    resposta_correta TEXT
);

INSERT INTO simuladoQuestões (ano_prova, titulo_questao, texto_questao, imagem, referencia, questao, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, resposta_correta) 
VALUES
(2016, null, null, 'http://127.0.0.1:5500/media/img/img-simulado/questao25.jpeg', 'ROTELLA, M. Marilyn, 1962. Disponivel em: www.nyu.edu. Acesso em: 30 maio 2016.', 'ROTELLA, M. Marilyn, 1962. Disponivel em: www.nyu.edu. Acesso em: 30 maio 2016.', 'A técnica da décollage, utilizada pelo artista Mimmo Rotella em sua obra Marilyn, é um procedimento artístico representativo da década de 1960 por:', 'é a opção d) fazer conviver campos de expressão diferentes e integrar novos significados. A décollage é uma técnica que consiste em aplicar superfícies umas sobre as outras e depois “descolar” camadas de papel a fim de revelar as superfícies que estão ocultas. Assim, é um procedimento diferente da colagem, mas que se relaciona com ela e tem também a intenção de aliar diversos tipos de comunicação e expressão, trazendo novas interpretações.'),
(2017, null, null, 'http://127.0.0.1:5500/media/img/img-simulado/questao26.jpg', 'Flávio de Carvalho. New Look, Experiência nº3, 1956', 'Em 1956, o artista Flávio de Resende Carvalho desfilou pela Avenida Paulista com o traje New Look uma proposta tropical para o guarda-roupa masculino. Suas obras mais conhecidas são relacionadas às performances. A imagem permite relacionar como características dessa manifestação artística o uso:', 'é a opção e) do corpo, da provocação e da moda. O artista usa a moda com o objetivo de trazer uma nova proposta de vestimenta para os homens; usa seu corpo como instrumento e suporte para comunicar pela arte; e usa também a provocação pois propõe um tipo de traje que não era utilizado por homens, e sim considerado uma "roupa feminina".'),
(2019, null, 'Contrabando, fraudes, roubos era o cotidiano das Minas, mas no ano de 1725 seu grau foi alarmante. O próprio governador, D. Lourenço de Almeida, foi um infatigável contrabandista de diamantes. (...) Na corte, nos mares, nos mercados, padres da Igreja, homens de Estado, mercadores, mineiros, senhores de engenho, lojistas, profissionais e artesãos acei tavam a prática do contrabando como algo inevi tável. A Metrópole procurou continuamente, sem sucesso, controlar essas fraudes.', null, 'Anita Novinsky, Ser Marrano em Minas Colonial.', 'São elementos, respectivamente, ligados aos contra bandistas de ouro na Colônia e à fiscalização metro politana:', 'a) CORRETA. O “santo do pau oco” foi utilizado pelos contra bandistas para escapar da vigilância metropolitana. Ouro não tributado, diamantes e pedras preciosas poderiam ser escondidos nessas obras de arte e pos sibilitar facilidades de fuga para os circulantes. Co mo forma de evitar o contrabando, a Coroa portu guesa criou as Casas de Fundição, proibindo a circulação do ouro em pó, medida que gerou revoltas dos mineradores.'),
(2016, null, 'Os sociólogos franceses Luc Boltanski e Ève Chiapello, em sua obra intitulada O novo espírito do capitalismo (2009), afirmam que a nova política de contratação e as novas organizações da estrutura empresarial (que é global) permitem que o empre gador, ao subcontratar a mão de obra, possa ocultar que é o empregador. É o caso de grandes empresas norte-americanas de celulares que transferiram sua produção para empresas fornecedoras na China. [...] Ou seja, levam a alterações contratuais de trabalho que, ao facilitarem os trâmites e a burocracia para a demissão de empregados, como é o caso dos chamados temporários, aumentam a sensação de insegurança dos trabalhadores.', null,  'ARAÚJO, Silvia Maria de; BRIDI, Maria Aparecida; MOTIM, Benilde Lenzi. Sociologia. São Paulo: Scipione, 2016. p. 152.', 'Essa nova estratégia de se produzir:', 'e) CORRETA. A flexibilização das leis que regulam as atividades laborais resulta em aumento da assimetria nas relações entre capital e trabalho, dificultando especialmente a ação de sindicatos em favor da classe de trabalhadores e trabalhadoras.'),
(2020, null, 'Os homens estão no interior desde a infância, acorrentados pelas pernas e pelo pescoço, de modo que não podem mudar de lugar nem voltar a cabeça para ver algo que não esteja diante deles. A luz lhes vem de um fogo que queima por trás deles, ao longe, no alto. Entre os prisioneiros e o fogo, há um caminho que sobe.', null, 'Trecho do Mito da Caverna, Platão.', 'A alegoria da caverna, de Platão, além de ser um texto de teoria do conhecimento, é também um texto político. No sentido político, é correto afirmar que Platão sustentava um modelo:', 'd) CORRETA. O único modelo político que está relacionado à alegoria da caverna é o aristocrático. Nessa alegoria está presente a figura de um homem (o filósofo) que, por ter conhecido a luz (a verdade), pode conduzir os outros homens que vivem na caverna e que conhecem somente as sombras da realidade.'), 
(2020, null, '"[...] desde Aristóteles, o ideal da lógica tem sido encontrar as condições necessárias para que, de proposições verdadeiras, se obtenham conclusões verdadeiras. E é apenas o método dedutivo que oferece essa possibilidade e garantia. [...] a dedução é um modo de raciocinar, argumentar e demonstrar em que a conclusão é uma consequência lógica das premissas [...]".', null, 'COTRIM, Gilberto; FERNANDES, Mirna. Fundamentos de filosofia – 4ª ed. São Paulo: Saraiva, 2016, p. 109.', ' b) CORRETA. O método dedutivo é um tipo de estrutura de raciocínio lógico que, para chegar a uma conclusão específica, utiliza uma ideia generalista. Ele parte de um conhecimento amplo e chega a outro, particular, com o auxílio dos chamados axiomas e teoremas.'),
(2021, null, '"Podemos facilmente perdoar uma criança que tem medo do escuro; a real tragédia da vida é quando os homens têm medo da luz." - Platão', null, null, 'A opinião (doxa, em grego), no pensamento de Platão representa um saber sem fundamentação metódica. É um saber que possui sua origem:', 'b) CORRETA. No pensamento de Platão, a opinião (doxa) é um saber que não possui fundamentação metódica e é baseada nas impressões sensíveis, formando o conhecimento inferior no modelo hierárquico do saber.',
(2021, null, '“A Segunda Revolução Industrial, no final do século XIX e início do século XX, nos EUA, período em que a eletricidade passou gradativamente a fazer parte do cotidiano das cidades e a alimentar os motores das fábricas, caracterizou-se pela administração científica do trabalho e pela produção em série.”', null, 'MERLO, A. R. C.; LAPIS, N. L. A saúde e os processos de tra balho no capitalismo: reflexões na interface da psicodinâmica do trabalho e a sociologia do trabalho. Psicologia e Sociedade, n. 1, abr. 2007.', 'De acordo com o texto, na primeira metade do século XX, o capitalismo produziu um novo espaço geoeconômico e uma revolução que está relacionada com a:', ' b) técnica de produção fordista, que instituiu a divi são e a hierarquização do trabalho, em que cada trabalhador realizava apenas uma etapa do pro cesso produtivo.'),
(2021, null, 'Chegança - Sou Pataxó, Sou Xavante e Carriri, Ianomâmi, sou Tupi Guarani, sou Carajá. Sou Pancaruru, Carijó, Tupinajé, Sou Potiguar, sou Caeté, Ful-ni-ô, Tupinambá! Eu atraquei num porto muito seguro, Céu azul, paz e ar puro... Botei as pernas pro ar. Logo sonhei que estava no paraíso, Onde nem era preciso dormir para sonhar. Mas de repente me acordei com a surpresa: Uma esquadra portuguesa veio na praia atracar. Da grande-nau Um branco de barba escura, Vestindo uma armadura me apontou pra me pegar. E assustado dei um pulo da rede, Pressenti a fome, a sede, Eu pensei: “vão me acabar”. Levantei-me de Borduna já na mão. Aí, senti no coração, O Brasil vai começar.', null, 'NÓBREGA, A.; FREIRE, W. CD Pernambuco falando para o mundo, 1998', 'A letra da canção apresenta um tema recorrente na história da colonização brasileira, as relações de poder entre portugueses e povos nativos, e representa uma crítica à ideia presente no chamado mito', ' e) do encontro, que identifica a colonização portu guesa como pacífica em função das relações de troca estabelecidas nos primeiros contatos entre portugueses e nativos.'),
(2020, null, null, null, null, 'Nos livros Harry Potter, um anagrama do nome do personagem “TOM MARVOLO RIDDLE” gerou a frase “I AM LORD VOLDEMORT”. Suponha que Harry quisesse formar todos os anagramas da frase “I AM POTTER”, de tal forma que as vogais e consoantes aparecessem sempre intercaladas, e sem considerar o espaçamento entre as letras. Nessas condições, o número de anagramas formados é dado por:', 'é a opção e) 4! 5! / 2 A questão pede anagramas com vogais e consoantes intercaladas, mas uma das consoantes, a letra "T", se repete. Ao contarmos as permutações de todas as consoantes, precisamos dividir o total por 2 para eliminar as duplicações causadas por essa repetição. Portanto, o número total de anagramas é: 4!×5! / 2'),
(2020, null, 'A Pesquisa Nacional por Amostra de Domicílios (Pnad) é uma pesquisa feita anualmente pelo IBGE, exceto nos anos em que há Censo. Em um ano, foram entrevistados 363 mil jovens para fazer um levantamento sobre suas atividades profissionais e/ou acadêmicas. Os resultados da pesquisa estão indicados no gráfico.', 'http://127.0.0.1:5500/media/img/img-simulado/questao36.jpeg', null, 'De acordo com as informações dadas, o número de jovens entrevistados que trabalha é', ' é a opção c) 213 444. Dado: número total de entrevistados: 363 000. Ideia 1: percentual dos que trabalham. Trabalha e estuda = 13,6% Somente trabalha = 45,2% Total que trabalham = 13,6 + 45,2 = 58,8% Ideia 2: 58,8% de 363 000. Gráfico Jovens em atividade entre 15 e 29 anos Portanto, o número de jovens entrevistados que trabalha é 213 444.'),
(2020, null, 'Uma empresa de ônibus utiliza um sistema de vendas de passagens que fornece a imagem de todos os assentos do ônibus, diferenciando os assentos já vendidos, por uma cor mais escura, dos assentos ainda disponíveis. A empresa monitora, permanentemente, o número de assentos já vendidos e compara-o com o número total de assentos do ônibus para avaliar a necessidade de alocação de veículos extras. Na imagem tem-se a informação dos assentos já vendidos e dos ainda disponíveis em um determinado instante.', 'http://127.0.0.1:5500/media/img/img-simulado/questao37.png', null, 'A razão entre o número de assentos já vendidos e o total de assentos desse ônibus, no instante considerado na imagem, é:', 'opção a) 16/42 Razão é uma divisão na forma de uma fração e estamos em busca da seguinte razão: Razão entre o número de assentos já vendidos e o total de assentos desse ônibus, no instante considerado na imagem
De acordo com a imagem, temos: 16 vendidos em um total de 42 lugares. Por isso, a razão procurada é 16/42.'),
(null, null, 'Uma das informações que pode auxiliar no dimensionamento do número de pediatras que devem atender em uma Unidade Básica de Saúde (UBS) é o número que representa a mediana da quantidade de crianças por família existente na região sob sua responsabilidade. O quadro mostra a distribuição das frequências do número de crianças por família na região de responsabilidade de uma UBS.', 'http://127.0.0.1:5500/media/img/img-simulado/questao38.png', null, 'O número que representa a mediana da quantidade de crianças por família nessa região é:', ' opção b) 1,5. Somando as frequências temos: 100 + 400 + 200 + 150 + 100 + 50 = 1000 Como o número de elementos é par, a mediana será a média aritmética entre os dois termos centrais, tempo organizado os dados de forma crescente. Os termos centrais serão as posição 500 e 501. Da tabela temos que o número de crianças por família na posição 500 é 1, enquanto para 501 é 2. A mediana é: 1+2/2 = 3/2 = 1,5'),
(2020, null, 'Pesquisadores da Universidade de Tecnologia de Viena, na Áustria, produziram miniaturas de objetos em impressoras 3D de alta precisão. Ao serem ativadas, tais impressoras lançam feixes de laser sobre um tipo de resina, esculpindo o objeto desejado. O produto final da impressão é uma escultura microscópica de três dimensões, como visto na imagem ampliada.', 'http://127.0.0.1:5500/media/img/img-simulado/questao39.png', null, 'A escultura apresentada é uma miniatura de um carro de Fórmula 1, com 100 micrômetros de comprimento. Um micrômetro é a milionésima parte de um metro. Usando notação científica, qual é a representação do comprimento dessa miniatura, em metro?', A resposta correta é a opção b)),
(null, null, 'Um designer de jogos planeja um jogo que faz uso de um tabuleiro de dimensão n x n, com n >= 2, no qual cada jogador, na sua vez, coloca uma peça sobre uma das casas vazias do tabuleiro. Quando uma peça é posicionada, a região formada pelas casas que estão na mesma linha ou coluna dessa peça é chamada de zona de combate de uma peça colocada em uma das casas de m tabuleiro de dimensão 8 x 8.', 'http://127.0.0.1:5500/media/img/img-simulado/questao40.png', null, 'O tabuleiro deve ser dimensionado de forma que a probabilidade de se posicionar a segunda peça aleatoriamente, seguindo a regra do jogo, e esta ficar sobre a zona de combate da primeira, seja inferior a 1/5. A dimensão mínima que o designer deve adotar para esse tabuleiro é:', 'Gabarito explicado: A resposta correta é a opção d) 10 x 10.'), 
(2018, null, 'O sonorizador é um dispositivo físico implantado sobre a superfície de uma rodovia de modo que provoque uma trepidação e ruído quando da passagem de um veículo sobre ele, alertando para a situação atípica à frente, como obras, pedágios ou travessia de pedestres. Ao passar sobre os sonorizadores, a suspensão do veículo sofre vibrações que produzem ondas sonoras, resultando em um barulho peculiar. Considere um veículo que passe com velocidade constante igual a 108 km/h sobre um sonorizador cujas faixas são separadas por uma distância de 8 cm', null, null, 'A frequência da vibração do automóvel percebida pelo condutor durante a passagem nesse sonorizador é mais próxima de:', 'Gabarito explicado: A resposta correta é a opção c) 375 hertz.' ),
(null, null, 'Um homem tenta levantar uma caixa de 5kg, que está sobre uma mesa, aplicando uma força vertical de 10N. Nessa situação, o valor da força que a mesa aplica na caixa é: (g=10 m/s^2).', 'http://127.0.0.1:5500/media/img/img-simulado/questao42.png', null, 'Gabarito explicado: A resposta correta é a opção d) 40 N.'), 
(2016, null, 'As notas musicais podem ser agrupadas de modo a formar um conjunto. Esse conjunto pode formar uma escala musical. Entre as diversas escalas existentes, a mais difundida é a escala diatônica, que utiliza as notas denominadas dó, ré, mi, fá, sol, lá e si. Essas notas estão organizadas em ordem crescente de alturas, sendo a nota dó a mais baixa e a nota si a mais alta.', null, null, 'Considerando uma mesma oitava, a nota si é a que tem menor:', 'A resposta correta é a opção e) comprimento de onda. Ela possui a maior frequência (f), e o comprimento de onda é inversamente proporcional à frequência, então, das notas citadas no texto acima, ela possui o menor comprimento de onda.'), 
(2020, null, null, null, null, 'Alguns modelos mais modernos de fones de ouvido têm um recurso, denominado “cancelador de ruídos ativo”, constituído de um circuito eletrônico que gera um sinal sonoro semelhante ao sinal externo (ruído), exceto pela sua fase oposta. Qual fenômeno físico é responsável pela diminuição do ruído nesses fones de ouvido?', 'a opção d) Interferência. Os fones emitem ondas em oposição de fase com as ondas indesejadas (ruído), interferindo, assim, de forma destrutiva.'),
(2019, null, '1O gráfico a seguir representa uma onda sonora que se propaga com uma velocidade de 340 m/s.', 'http://127.0.0.1:5500/media/img/img-simulado/questao45.png', null,'Sabendo que o ser humano, em média, consegue ouvir sons de frequência em um espectro de 20 Hz até 20000 Hz, essa onda sonora:', 'Gabarito explicado: A resposta correta é a opção c) pode ser ouvida pelo ser humano, pois apresenta frequência de aproximadamente 11300 Hz. Calculo da questão' ),
(null, null, null, null, null, 'Suponha que uma partícula se move com aceleração escalar de 3 m/s2 em uma trajetória circular cujo raio é igual a 24 m. No instante t = 0, a velocidade dessa partícula é igual a 6 m/s. Assim, determine o módulo da aceleração tangencial e marque a alternativa correta.', ' é a opção b) 3m/s2 Em uma trajetória curva, a aceleração tangencial possui o mesmo módulo, ou seja, o mesmo valor da aceleração escalar, portanto o valor da aceleração tangencial é 3 m/s2.' ), 
(null, null,  'As abelhas utilizam a sinalização química para distinguir a abelha-rainha de uma operária, sendo capazes de reconhecer diferenças entre moléculas. A rainha produz o sinalizador químico conhecido como ácido 9-hidroxidec-2-enoico, enquanto as abelhas-operárias produzem o ácido 10-hidroxidec-2-enoico. Nós podemos distinguir as abelhas-operárias e rainhas por sua aparência, mas, entre si, elas usam essa sinalização química para perceber a diferença. Pode-se dizer que veem por meio da química.', null, 'LE COUTEUR, P.; BURRESON, J. Os botões de Napoleão: as 17 moléculas que mudaram a história. Rio de Janeiro: Jorge Zahar, 2006 (adaptado).', 'As moléculas dos sinalizadores químicos produzidas pelas abelhas rainha e operária possuem diferença na', ' resposta correta é a opção a) fórmula estrutural. As moléculas do ácido 9-hidroxidec-2-enoico (produzido pela rainha) e do ácido 10-hidroxidec-2-enoico (produzido pelas operárias) diferem na posição de um grupo hidroxila (-OH) ao longo da cadeia carbônica. Essa diferença de posição altera a fórmula estrutural das moléculas, enquanto a fórmula molecular (o número de átomos de cada elemento) permanece a mesma.'  ), 
